# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RUN DMcC
email: darren@rundmcc.com
description: Personal running blog of Darren McCall (AKA RUN DMcC).
baseurl: ""
url: "http://rundmcc.github.io"
twitter_username: DarrenMcCall
github_username:  rundmcc

# Build settings
markdown: kramdown

# Outputting
permalink: :year/:title
